### ISSUE TITLE
Majority of topics marked with ⛔ or ⛏️

### ISSUE THREAD

**Issue by simonmandlik** [draliii/oi-mszz#1]
It seems to me that in the new version most of the topics are not done yet. Can you update?

How to reproduce:

1) Visit [this url](https://github.com/draliii/oi-mszz)

**Comment by KSonny4** [comment]
Could you @Sheemon7 please make a pull request with added materials?

**Comment by simonmandlik** [comment]
Not relevant for our project anymore, closing

**Comment by KSonny4** [comment]
:(
